config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  # root to: "home#index"
  root "high_voltage/pages#show", id: 'home'
  
  devise_for :users, controllers: { sessions: "users/sessions" }
  
  resources :users
  
  resources :books

  # resources :conversations do
  #   resources :messages
  # end

  get "/users/:id/matches" => "users#matches", as: :user_matches 
  get "/users/:id/stack" => "users#stack", as: :user_stack

  get "/users/:id/stack/:book_id/like" => "users#like", as: :user_like
  get "/users/:id/stack/:book_id/dislike" => "users#dislike", as: :user_dislike

  get "/users/:id/stack/:book_id/unlike" => "users#unlike", as: :unlike_book

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100" }, :default_url => "/images/p.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage/
  # validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/, /jpg\Z/, /JPG\Z/]
  
  has_many :conversations, :foreign_key => :sender_id
  
  has_many :votes, -> { includes :book }, dependent: :destroy
  
  has_many :owned_books, ->{ uniq }, class_name: "Book", dependent: :destroy, inverse_of: :owner

  has_many :voted_books, -> { uniq }, through: :votes, source: :book

  has_many :given_likes, -> { where(liked: true) }, class_name: "Vote"

  has_many :ungiven_likes, -> { where(liked: false) }, class_name: "Vote"

  has_many :liked_books, -> { uniq }, through: :given_likes, source: :book

  has_many :disliked_books, -> { uniq }, through: :ungiven_likes, source: :book

  has_many :received_votes, through: :owned_books, source: :votes

  has_many :received_likes, ->{ where(liked: true) }, through: :owned_books, source: :votes

  has_many :books_liked, through: :received_likes, source: :book

  has_many :likers, -> { uniq }, through: :received_likes, source: :user

  has_many :liked_users, -> { uniq }, through: :liked_books, source: :owner

  # GEOCODER
  geocoded_by :ip_address,
      :latitude => :latitude, :longitude => :longitude

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.city    = geo.city
      obj.state   = geo.state
      obj.zipcode = geo.postal_code
      obj.country = geo.country
      obj.street  = geo.address
    end
  end

  # after_validation :geocode, :reverse_geocode

  # SCOPES
  scope :people_in_range, -> (user) { where("id != ? and ", user.id ).near( [ user.latitude, user.longitude ], user.range ) }
  scope :all_likers, -> { joins(:votes).where('votes.liked = ?', true) }
  scope :all_voters, -> { joins(:votes).where('votes.user_id != ?', nil ) }

  # Validations

  def address
     [street, city, state, country].compact.join(', ')
  end

  def address_changed?
     [street.changed?, city.changed?, state.changed?, country.changed?].count(true) > 0
  end
  

  def has_coordinates
    longitude.present? and latitude.present?
  end

  def matches
    liked_books.where(user_id: likers.ids)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
    end
  end

  def bookstack
    if geocoded?
      bkids = owned_books.ids+voted_books.ids
      usrids = nearbys(range).flat_map{|usr| usr.id}
      # usrids = User.people_in_range(self).pluck(:id)
      Book.where("user_id in (?) AND id not in (?)", usrids, bkids)
    else
      puts "not geocoded"
    end
  end


  private
    def self.ransackable_scopes(auth_object = nil)
      %i(active hired_since all_likers)
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :stack, :matches, :edit, :update, :destroy, :like, :dislike, :unlike]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end


  def matches
  end

  def stack
  end

  def like
      @book = Book.find(params[:book_id])
      @user.liked_books<<@book
      redirect_to :back, notice: "Successfully Liked Book"
  end

  def dislike
      @book = Book.find(params[:book_id])
      @user.disliked_books<<@book
      redirect_to :back, notice: "Successfully disLiked Book"
  end

  def unlike
      @book = Book.find(params[:book_id])
      @user.liked_books.delete(@book)
      redirect_to :back, notice: "Book has been unliked"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params[:user]
    end
end

app/views/users/_books_liked.html.erb
<div class="row">
    <div id="books_liked" class="center-block smitify owl-carousel owl-theme">
        <% @user.books_liked.each do |book| %>
            <div class="item"><%= link_to image_tag(book.image_url, class: "lazyOwll"), book_path(book) %></div>
        <% end -%>
    </div>
</div>

<div class="clearfix"></div><hr>

<div class="row">
  <!-- <div class="col-sm-8"> -->
    <div class="btn-group centerwrap customNavigation" data-toggle="buttons">
      <label class="btn btn-primary active prev">
        <input  type="checkbox" autocomplete="off" checked> Previous
      </label>
      <label class="btn btn-primary next">
        <input  type="checkbox" autocomplete="off"> Next
      </label>
      <label class="btn btn-primary play">
        <input  type="checkbox" autocomplete="off"> Autoplay
      </label>
      <label class="btn btn-primary stop">
        <input  type="checkbox" autocomplete="off"> Stop
      </label>
    </div>
  <!-- </div> -->

</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, autofocus: true %>
    <%= f.input :email, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_liked_books.html.erb
<div class="row">
  
  <div id="liked_books" class="centerwrap smitify owl-carousel owl-theme">
        <% @user.liked_books.each do |book| %>
            <div class="item">
              <hr>
              <%= link_to image_tag(book.image_url, class: "lazyOwll"), book_path(book) %>
              <hr>
              <%=link_to "Unlike", unlike_book_path(@user, book), class: "btn btn-success btn-block" %>  
            </div>
            <div class="clearfix"></div>
        <% end -%>
  </div>
</div>

<div class="clearfix"></div><hr>

<div class="row">
  <!-- <div class="col-sm-8"> -->
    <div class="btn-group centerwrap customNavigation" data-toggle="buttons">
      <label class="btn btn-primary active prev">
        <input  type="checkbox" autocomplete="off" checked> Previous
      </label>
      <label class="btn btn-primary next">
        <input  type="checkbox" autocomplete="off"> Next
      </label>
      <label class="btn btn-primary play">
        <input  type="checkbox" autocomplete="off"> Autoplay
      </label>
      <label class="btn btn-primary stop">
        <input  type="checkbox" autocomplete="off"> Stop
      </label>
    </div>
  <!-- </div> -->

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/matches.html.erb
<hr>
<div class="row">
    <div id="owl-demo" class="owl-carousel owl-theme">
        <% @user.matches.each do |book| %>
            <div class="item">
                <div class="col-sm-7">
                    <%= link_to image_tag(book.image_url), book_path(book) %>
                </div>
                <div class="col-sm-5">
                    <h4><%= link_to book.title, book_path(book) %></h4>
                    <hr>
                    <blockquote >
                        <p><%= book.description %></p>
                        <footer><cite title="Source Title"><%= book.author %> </cite></footer>
                    </blockquote>
                    <div class="clearfix"></div><hr>
                    <h5>Potential Trades <span class="pull-right"><%= @user.distance_to(book.location).round(1) %> miles</span></p>
                    <div class="clearfix"></div><hr>
                    <div id="owl-mini-demo">
                        <% book.owner.liked_books.where(owner: @user).each do |obk| %>
                            <div class="item"><%= link_to image_tag(obk.image_url), book_path(obk), class: "imgs-thumbnail" %></div>
                        <% end -%>
                    </div>
                </div>
                    <div class="clearfix"></div><hr>
            </div>
        <% end -%>
    </div>
</div>

app/views/users/new.html.erb
<h2>Log in</h2>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/show.html.erb
<hr>
<div class="row">
  <div class="col-sm-6 text-left">  
      <h3>Welcome <%=@user.name.capitalize %></h3>
  </div>
   <div class="col-sm-6 text-right">
     <h3><%=@user.email %></h3>
   </div> 
</div>

<div class="clearfix"></div><hr>

<div class="row">
    <div class="col-sm-3">
        <%=image_tag(@user.avrl, class: "img-thumbnail meimg")%>
    </div>
    <div class="col-sm-9">
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>  
                  <td># of Owned Books</td>
                  <td># of Liked Books</td>
                  <td># of Disliked Books</td>
                  <td># of Books Liked by Others</td>
                  <td># of Liked Users</td>
                  <td># of Users Liked</td>
                </tr>
              </thead>
              <tbody>
                <tr> 
                   <td><%=@user.owned_books.count %></td>
                   <td><%=@user.liked_books.count %></td>
                   <td><%=@user.disliked_books.count %></td>
                   <td><%=@user.books_liked.count %></td>
                   <td><%=@user.liked_users.count %></td>
                   <td><%=@user.likers.count %></td>
                </tr>
              </tbody>
            </table>
        </div>
    </div>
    
</div>

<div class="clearfix"></div><hr>

<div class="row">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified col-sm-11" id="myTabs" role="tablist">
    <li role="presentation" class="active"><a href="#all_available" aria-controls="all_available" role="tab" data-toggle="tab">Liked Books</a></li>
    <li role="presentation"><a href="#passenger_rides" aria-controls="passenger_rides" role="tab" data-toggle="tab">Books Liked</a></li>
    <li role="presentation"><a href="#driver_rides" aria-controls="driver_rides" role="tab" data-toggle="tab">Liked Users</a></li>
    <!-- <li role="presentation"><a href="#driver_cal" aria-controls="driver_cal" role="tab" data-toggle="tab">Calendar</a></li> -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content col-sm-10 col-sm-offset-1">
    <div role="tabpanel" class="tab-pane active" id="all_available">
        <%= render partial: "liked_books", locals: {user: @user} %>
    </div>
    <div role="tabpanel" class="tab-pane" id="passenger_rides">
        <%= render partial: "books_liked", locals: {user: @user} %>
    </div>
    <div role="tabpanel" class="tab-pane" id="driver_rides">
        <%= render partial: "liked_users", locals: {user: @user} %>
    </div>
    
  </div>
</div>

<div class="clearfix"></div><hr>

app/views/users/stack.html.erb
<hr>
<div class="row">
    <div id="owl-demo" class="owl-carousel owl-theme">
        <% @user.bookstack.each do |book| %>
            <div class="item">
                <div class="col-sm-4 ">
                    <%= link_to image_tag(book.image_url, class: "bookpic"), book_path(book) %>
                </div>
                <div class="col-sm-7 panelify">
                    <h4><%= link_to book.title, book_path(book) %></h4>
                    <hr>
                    <blockquote >
                        <!-- <p><%= book.description %></p> -->
                        <p><%= ActionView::Base.full_sanitizer.sanitize(book.description) %></p>
                        <footer><cite title="Source Title"><%= book.author %></cite></footer>
                    </blockquote>
                    <div class="clearfix"></div><hr>
                    <h5>User Distance <span class="pull-right"><%= @user.distance_to(book.location).round(1) %> miles</span></h5>
                    <div class="clearfix"></div><hr>
                    <div class="media row media well">
                      <div class="col-sm-3 media-left">
                        <%= link_to image_tag(book.owner.avrl, class: "media-object"), user_path(book.owner) %>
                      </div>
                      <div class="media-body col-sm-7">
                        <h4 class="media-heading"><%= link_to book.owner.name.upcase, user_path(book.owner) %></h4>
                        <ul>
                            <li><%= book.owner.email %></li>
                            <li>
                                
                            </li>
                        </ul>
                      </div>
                    </div>
                    <div class="clearfix"></div> <hr>
                    <div class="row">
                        <div class="col-sm-6">
                            <%=link_to "Like", user_like_path(@user, book), class: "btn btn-success btn-block" %>
                        </div>
                        <div class="col-sm-6">
                            <%=link_to "Nope!", user_dislike_path(@user, book), class: "btn btn-danger btn-block" %>
                        </div>
                    </div>
                </div>
            </div>
        <% end -%>
    </div>
</div>