config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  # root to: "home#index"
  root "high_voltage/pages#show", id: 'home'
  
  devise_for :users, controllers: { sessions: "users/sessions" }
  
  resources :users
  
  resources :books

  # resources :conversations do
  #   resources :messages
  # end

  get "/users/:id/matches" => "users#matches", as: :user_matches 
  get "/users/:id/stack" => "users#stack", as: :user_stack

  get "/users/:id/stack/:book_id/like" => "users#like", as: :user_like
  get "/users/:id/stack/:book_id/dislike" => "users#dislike", as: :user_dislike

  get "/users/:id/stack/:book_id/unlike" => "users#unlike", as: :unlike_book

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "SwipeTrade", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Profile", user_path(current_user) %>
              </li>
              <li>
                <%= link_to "Matches", user_matches_path(current_user) %>
              </li>
              <li>
                <%= link_to "BookStack", user_stack_path %>
              </li>
              <li>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign In", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Register", new_user_registration_path %>            
              </li>
            <% end -%>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>

  <div class="container-fluid">
    <%= yield %>    
  </div>
  
  <%= render "javascript" %>
</body>
</html>